---
- hosts: node1
  gather_facts: no
  tasks:
  - name: Wait for SSH port open
    local_action: wait_for port=22 host={{ansible_ssh_host}} delay=10
  #- local_action: wait_for port=22 host="{{ ansible_ssh_host | default(inventory_hostname) }}" search_regex=OpenSSH delay=10
  - name: Install pip3, tmux, libgeos-dev
    become: true
    apt: name={{item}} state=latest update_cache=yes
    with_items:
      - python3-pip
      - tmux
      - libgeos-dev
  - name: Install fiona, shapely, couchdb, textblob, tweepy
    become: true
    command: pip3 install {{item}}
    with_items:
      - fiona
      - shapely
      - couchdb
      - textblob
      - tweepy