---

- hosts: webserver
  gather_facts: no
  vars_files:
    - vars/variable.yml
  tasks:
  - name: Wait for SSH port open
    local_action: wait_for port=22 host={{ansible_ssh_host}} delay=10
  - name: Install pip3, tmux, libgeos-dev, git
    become: true
    apt: name={{item}} state=latest update_cache=yes
    with_items:
      - python3-pip
      - tmux
      - libgeos-dev
      - git

  - name: Install fiona, shapely, couchdb, textblob, tweepy
    become: true
    command: pip3 install {{item}}
    with_items:
      - fiona
      - shapely
      - couchdb
      - textblob
      - tweepy
    # mount external volume to instance
  - name: Create ext4 file system on the volumn
    command: sudo mkfs -t ext4 /dev/vdb
  - name: Make new dir for new Volumn
    command: sudo mkdir /mnt/data
  - name: Mount volumn in to data
    command: sudo mount /dev/vdb /mnt/data

    # install couchdb
  - name: Copy couchdb installation script
    copy: src=install-couchdb.sh dest=~/
  - name: Copy couchdb reinit script
    copy: src=reinit-couchdb.sh dest=~/
  - name: Remove sympolic /usr/lib/erlang/man
    become: true
    file: path=/usr/lib/erlang/man state=absent
  - name: Install and run Couchdb
    become: true
    command: sh install-couchdb.sh

    # pull the source code
  - name: Copy SSH private key file
    copy: src=team25.key
          dest=~/
          mode=0400
  - name: Checkout application from Github
    git: repo=git@github.com:lchlnd/comp90024-project-2.git
         dest=~/src/
         accept_hostkey=yes
         key_file=team25.key
         update=no