---
- hosts: webserver
  gather_facts: no
  tasks:
  - name: Wait for SSH port open
    local_action: wait_for port=22 host={{ansible_ssh_host}} delay=10
  - name: Install pip3, tmux, libgeos-dev, git, apache2
    become: true
    apt: name={{item}} state=latest update_cache=yes
    with_items:
      - python3-pip
      - tmux
      - libgeos-dev
      - git
      - apache2
  - name: Install fiona, shapely, textblob, tweepy
    become: true
    command: pip3 install {{item}}
    with_items:
      - fiona
      - shapely
      - textblob
      - tweepy
  - name: Copy SSH private key file
    copy: src=team25.key
          dest=~/
          mode=0400
  - name: Checkout application from Github
    git: repo=git@github.com:lchlnd/comp90024-project-2.git
         dest=~/src/
         accept_hostkey=yes
         key_file=team25.key
         update=no
  - name: Link to database node
    become: true
    shell: ssh -f -L localhost:15984:127.0.0.1:5984 ubuntu@115.146.93.177 -N -i team25.key chdir=/home/{{ansible_ssh_user}}/src/ &
  #- name: Start process of gathering data from db
  #  command: python3 process.py chdir=/home/{{ansible_ssh_user}}/src/
  - name: Copy web to root folder
    become: true
    shell: cd ./src/web/; cp -r * /var/www/html/
  - name: start apache2 service
    service: name=apache2 state=started
  - debug:
      msg: "Access web application as {{ ansible_ssh_host }}"